config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get '/monsters', to: 'monsters#index'
  #get '/monsters/:id', to: 'monsters#show', as: 'monster'
  resources :monsters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monster.rb
class Monster < ApplicationRecord
  validates :name, presence: {message: ":You must name the Beast."} 
  validates :hunger, presence: true
  validates :scare_factor, inclusion: 1..100 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  def index
    @monsters = Monster.all
    render 'monsters/index' #this is optional!!
  end

  def show ;end

  def new 
    @monster = Monster.new
  end

  def create 
    @monster = Monster.new(monster_params)
    if @monster.save
      redirect_to monster_path(@monster)
    else 
      render :new
    end
  end

  def edit;end

  def update 
    @monster.update(monster_params)
    redirect_to monster_path(@monster)
  end

  def destroy
    @monster.destroy
    redirect_to monsters_path
  end

  private 

  def set_monster 
    @monster = Monster.find_by_id(params[:id])
  end

  def monster_params
    params.require(:monster).permit(:name, :scare_factor, :hunger)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonsterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monsters/_form.html.erb
  <%= form_for monster do |f| %> 
  <%= f.label "Name the Monster" %> 
  <%= f.text_field :name %>
  <%= f.label "Scare Factor" %> 
  <%= f.number_field :scare_factor %>
  <%= f.label "What Does it Hunger For?!" %> 
  <%= f.text_field :hunger %>
  <%= f.submit %>
<% end %>

app/views/monsters/edit.html.erb
<h1> Edit Your Spooky, Fearsome, or Dangerous Monster </h1>
<%= render 'form', monster: @monster %>

app/views/monsters/index.html.erb
<h1>HECKA MONSTERS!!!!!</h1>
<% @monsters.each do |monster| %>
  <p> <%= link_to monster.name, monster_path(monster)%> </p>
<% end %>
<h3> <%= link_to "Create a Monster?", new_monster_path %> </h3>

app/views/monsters/new.html.erb
<h1> Add a Spooky, Fearsome, or Dangerous Monster </h1>

<% if @monster.errors.any? %>

  <div id="error_explanation">
    <h2>
      <%= pluralize(@monster.errors.count, "error") %>
        blocked this monster from being saved:
    </h2>

    <ul>
      <% @monster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%>  
    </ul>
  </div>
<% end %>
  
<%= render 'form', monster: @monster %>

app/views/monsters/show.html.erb
<%=link_to "Home", monsters_path%>

<p>Name: <%=@monster.name%></p>
<p>Scare Factor: <%= @monster.scare_factor%></p>
<p>Hungry For: <%= @monster.hunger%></p>

<%= link_to "Edit", edit_monster_path(@monster)  %>
<h4><%= link_to "Destroy This Monster", monster_path(@monster), method: :delete  %></h4>